### ISSUE TITLE
Bump to Anchor v0.24.2

### ISSUE THREAD

**Issue by 0xcatrovacer** [ironaddicteddog/anchor-escrow#10]
Hi @ironaddicteddog,
Anchor recently identified a security issue which was fixed in Anchor v0.24.2 and using a version lower than that will cause this error in `Cargo.toml`

> failed to select a version for the requirement `anchor-lang = "^0.22.0"`
> candidate versions found which didn't match: 0.24.2
> location searched: crates.io index

The current escrow program is at Anchor v0.22.0 and it's best to bump to Anchor v0.24.2.

Can make a PR if you want.

**Comment by ironaddicteddog** [comment]
Yes, a PR will be welcome :)
