### ISSUE TITLE
Failed during anchor build

### ISSUE THREAD

**Issue by alphadev102** [ironaddicteddog/anchor-escrow#13]
I got following error during build project.

error[E0635]: unknown feature `proc_macro_span_shrink`

my anchor version is 0.25.0

plz help me.

**Comment by ironaddicteddog** [comment]
Hi, what is your Solana version? I suppose you need 1.10.x to build it successfully.

**Comment by alphadev102** [comment]
my solana version is 1.9.4
this is latest version.
