### ISSUE TITLE
Set Authority for Vault Account

### ISSUE THREAD

**Issue by brendan-mccaffrey** [ironaddicteddog/anchor-escrow#14]
Hello, I'm working on a separate (non-escrow) project, and been using this as a reference. 

I am facing an issue when trying to transfer the Token Account authority. In this codebase, this is relevant to the authority transfer of `vault_account` on [Line 45 of lib.rs](https://github.com/ironaddicteddog/anchor-escrow/blob/master/programs/anchor-escrow/src/lib.rs#L45).

Note: I am using different versions of anchor-spl, version 0.25.0, however I haven't found reason to believe this is the source of the issue.

In my example, the equivalent to [Line 156 of test.ts](https://github.com/ironaddicteddog/anchor-escrow/blob/master/tests/anchor-escrow.ts#L156) fails as the `_vault.owner` address is the Token Program, not the program PDA.

Any help is appreciated, thanks.

**Comment by ironaddicteddog** [comment]
Would it be possible that the authority is not set correctly?
