### ISSUE TITLE
there is a error when build this program

### ISSUE THREAD

**Issue by lucas7788** [ironaddicteddog/anchor-escrow#19]
my anchor version is anchor-cli 0.29.0

   Compiling bs58 v0.3.1
error[E0658]: use of unstable library feature 'build_hasher_simple_hash_one'
   --> src/random_state.rs:463:5
    |
463 | /     fn hash_one<T: Hash>(&self, x: T) -> u64 {
464 | |         RandomState::hash_one(self, x)
465 | |     }
    | |_____^
    |
    = note: see issue #86161 <https://github.com/rust-lang/rust/issues/86161> for more information
    = help: add `#![feature(build_hasher_simple_hash_one)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `ahash` due to previous error
warning: build failed, waiting for other jobs to finish...

**Comment by Matthammond96** [comment]
Facing the same error, using rust version 1.75.0

**Comment by ironaddicteddog** [comment]
Let me take a look. Thx for reproring
