### ISSUE TITLE
NFT purchase ?

### ISSUE THREAD

**Issue by easydeveloppement** [ironaddicteddog/anchor-escrow#3]
Hi !
I would like to write a rust contract for a NFT purchase action, using this example as a base.
My questions : 
1) For the NFT's royalties, do we need to code it manually or is it implicit in an instruction ?
2) If i understand well, instead of using spl_token::instruction::transfer for transfering Tokens, there is another instruction to be used to transfer SOL ? (or should i use SOL as an SPL Token ?)
Thanks !

**Comment by easydeveloppement** [comment]
Hi, thanks for your reply, once again.
I figured out for royalties that we have to compute them in the rust program, so that's my answer.

For the SOL transfer, i really don't manage to find any example... If you have an idea, it would be awesome, i explain what i did : 

1) in the ts script, added this line : 
systemProgram: anchor.web3.SystemProgram.programId,
(in the accounts array in the program.rpc.exchange() , at the end)

2) in the rust, added this line : 
pub system_program: AccountInfo<'info>,
in the 
#[derive(Accounts)]
pub struct Exchange<'info> 
section, at the end also.

And i get an error "program failed to complete". Sounds weird, i just added the system program in the accounts...

I also tried to use : 

// tentative d'envoi de sols
		let ix = anchor_lang::solana_program::system_instruction::transfer(
			&ctx.accounts.taker.to_account_info().key,
			&ctx.accounts.initializer.to_account_info().key,
			999999999,
		);

		SolanaProgram::invoke(
			&ix,
			&[
			ctx.accounts.taker.to_account_info().clone(),
			ctx.accounts.initializer.to_account_info().clone(),
			// ctx.accounts.system_program.to_account_info(),
			],
		)?;

i'm really not sure about the .clone() and .key, but i don't know what expect this transfer instruction, so very hard to guess.
If i remove the line pub system_program: AccountInfo<'info>, the program runs, but i get the error with escalation error (i think i miss a signature, but i don't understand which one since i have the taker signature, and the receiver signature should not be necessary to receive sol...)

Thanks for your reply !

**Comment by easydeveloppement** [comment]
i wonder something :

some accounts are declared like this : 
Account<'info, TokenAccount>,
others are declared like this : 
AccountInfo<'info>

may be there is a special way to declare system program account ? (like for token accounts)

**Comment by ironaddicteddog** [comment]
Hi, please refer to this document for more details

https://hackmd.io/@ironaddicteddog/solana-anchor-escrow
