### ISSUE TITLE
Failing Test Cases - Initialize Program State

### ISSUE THREAD

**Issue by maitreya2048** [ironaddicteddog/anchor-escrow#7]
Hi - Thank you for the Anchor Escrow article. I was able to build the program successfully but am failing all the test cases. The first test initialize program state fails with this error "Transaction simulation failed: Attempt to debit an account but found no record of a prior credit." I am attempting to run this on devnet with anchor-cli 0.20.1

**Comment by ironaddicteddog** [comment]
Hi, this means you don't have enough fund (lamports) in signer wallet. You might have to switch to localhost or ask for an airdrop on devnet:

```
$ solana config set -u devnet
$ solana airdop 1
```

**Comment by maitreya2048** [comment]
Hi - thank you for your reply. Maybe this is a naive question, but I am new to solana and its ecosystem.
Which wallet do you mean by signer wallet? and where is it configured?
I am assuming this is none of the wallets that are being generated inside the test cases.
I created a new wallet and added its address to the anchor.toml file under [provider]. I airdropped tokens to this wallet and it has sufficient amount of funds. I still see the above error.
Can you please clarify, really appreciate it!
