### ISSUE TITLE
Multiple exchange transactions

### ISSUE THREAD

**Issue by maitreya2048** [ironaddicteddog/anchor-escrow#8]
Hi - This is more of a question than an issue. If I wanted to start multiple such exchanges as described in your blog, I am assuming multiple Escrow accounts and vault accounts would be created. Does this statement lend to creating multiple vault accounts?

let (vault_authority, _vault_authority_bump) =
            Pubkey::find_program_address(&[ESCROW_PDA_SEED], ctx.program_id);

Since the ESCROW_PDA_SEED is fixed as "escrow", and the program_id is fixed, would it connect to the same vault in all such exchanges?
Something like this - 
 seeds = [b"escrow", user.key().as_ref()]

Do we need to add, lets say the first user as part of the seed, so it creates and finds those vault accounts specific to those users when called?

**Comment by ironaddicteddog** [comment]
Hi, this is a good suggestion. Would be great if you can open a PR for this.
